on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
